name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar lint (flake8)
        run: |
          pip install flake8
          flake8 src/ tests/

      - name: Rodar testes
        run: |
          pip install pytest pytest-cov
          pytest --cov=src/aws_utils tests/

      - name: Publicar cobertura no PR
        uses: actions/upload-artifact@v4
        with:
          name: cobertura
          path: .coverage